language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq lynx html2text
    - composer install

script: ./vendor/bin/phpunit
